# Generated by Django 4.1.7 on 2023-04-17 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8f4daf0a-fcb0-4b1f-96f1-fd052d0c621c'), primary_key=True, serialize=False),
        ),
    ]
