# Generated by Django 4.1.7 on 2023-04-17 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a2adab78-2419-40e5-a50a-4103950591bc'), primary_key=True, serialize=False),
        ),
    ]
