# Generated by Django 4.1.7 on 2023-04-17 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5ffd73f1-aa5a-4db9-8e8d-56da02563a91'), primary_key=True, serialize=False),
        ),
    ]
