version: '3.8'

services:
  app:
    build: .
    # image: python:3.8.10
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    volumes:
      - ./lb-mysql-data:/var/lib/mysql
      - /tmp/app/mysqld:/var/run/mysqld
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=${MYSQLname}
      - MYSQL_USER=${MYSQLuser}
      - MYSQL_PASSWORD=${MYSQLpwd}
      - MYSQL_ROOT_PASSWORD=${MYSQLpwd}
      - MYSQL_HOST=${MYSQLhost}